// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/dummy/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	resource "konntent-workspace-service/internal/app/dto/resource"
	event "konntent-workspace-service/pkg/event"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockService) Handle(ctx context.Context, dto *event.DummyEvent) (resource.DummyResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, dto)
	ret0, _ := ret[0].(resource.DummyResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockServiceMockRecorder) Handle(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockService)(nil).Handle), ctx, dto)
}
