version: '3.3'
services:
  konntent-workspace-service:
    image: cosmtrek/air
    command: -c=.air.app.toml
    working_dir: /app
    environment:
      - ENV=production
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - go-modules-volume:/go/pkg/mod
    networks:
      - network-sms-service
#    depends_on:
#      - rabbit-mq-node
    restart: always

  workspace-yugabyte:
    container_name: yb-workspace-master-n1
    image: yugabytedb/yugabyte:latest
    environment:
      POSTGRES_USER: konntent
      POSTGRES_PASSWORD: 345xyxyyayaqd3
      POSTGRES_DB: konntent-workspace
      PGDATA: /data/yb
      SERVICE_7000_NAME: yb-workspace-master
    command: |
      bash -c '
      mkdir -p /var/workspace/ybinit
      echo "create user '\''$${POSTGRES_USER}'\'' with password '\''$${POSTGRES_PASSWORD}'\'';" > /var/workspace/ybinit/01-usr.sql
      echo "create database $${POSTGRES_DB:-$${POSTGRES_USER}};             " > /var/workspace/ybinit/02-db.sql
      # start YugabyteDB
      bin/yugabyted start --listen 0.0.0.0 --daemon=false --initial_scripts_dir=/var/ybinit --tserver_flags=ysql_enable_auth=true
      '
    volumes:
      - yb-master-data-1:/var/workspace/ybinit
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    networks:
      - yb
    restart: unless-stopped


  workspace-integration-yugabyte:
    container_name: yb-workspace-integration-master-cluster
    image: yugabytedb/yugabyte:latest
    environment:
      POSTGRES_USER: yugabyte
      POSTGRES_PASSWORD: yugabyte
      POSTGRES_DB: integration
      PGDATA: /data/integration/yb
      SERVICE_7000_NAME: yb-workspace-integration-master
    command: |
      -c fsync=off
      -c synchronous_commit=off
      -c archive_mode=off
      -c wal_level=minimal
      -c shared_buffers=512MB
    volumes:
      - yb-integration-data:/var/workspace/ybinit
    ports:
      - "7001:7000"
      - "9001:9000"
      - "5434:5433"
      - "9043:9042"
    networks:
      - yb
    restart: unless-stopped

networks:
  yb:
    driver: bridge
  network-sms-service:
    driver: bridge

volumes:
  go-modules-volume:
  yb-master-data-1:
  yb-integration-data:
  yb-tserver-data-1:
