// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/httpclient/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	httpclient "konntent-workspace-service/pkg/httpclient"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// GetJSONHeaders mocks base method.
func (m *MockHTTPClient) GetJSONHeaders() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONHeaders")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetJSONHeaders indicates an expected call of GetJSONHeaders.
func (mr *MockHTTPClientMockRecorder) GetJSONHeaders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONHeaders", reflect.TypeOf((*MockHTTPClient)(nil).GetJSONHeaders))
}

// HandleException mocks base method.
func (m *MockHTTPClient) HandleException(resp *httpclient.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleException", resp)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleException indicates an expected call of HandleException.
func (mr *MockHTTPClientMockRecorder) HandleException(resp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleException", reflect.TypeOf((*MockHTTPClient)(nil).HandleException), resp)
}

// HandleRequest mocks base method.
func (m *MockHTTPClient) HandleRequest(ctx context.Context, req httpclient.Request) (*httpclient.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRequest", ctx, req)
	ret0, _ := ret[0].(*httpclient.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleRequest indicates an expected call of HandleRequest.
func (mr *MockHTTPClientMockRecorder) HandleRequest(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequest", reflect.TypeOf((*MockHTTPClient)(nil).HandleRequest), ctx, req)
}

// IsCustomErrorType mocks base method.
func (m *MockHTTPClient) IsCustomErrorType(errType string, err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCustomErrorType", errType, err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCustomErrorType indicates an expected call of IsCustomErrorType.
func (mr *MockHTTPClientMockRecorder) IsCustomErrorType(errType, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCustomErrorType", reflect.TypeOf((*MockHTTPClient)(nil).IsCustomErrorType), errType, err)
}

// IsSuccessStatusCode mocks base method.
func (m *MockHTTPClient) IsSuccessStatusCode(resp *httpclient.Response) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSuccessStatusCode", resp)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSuccessStatusCode indicates an expected call of IsSuccessStatusCode.
func (mr *MockHTTPClientMockRecorder) IsSuccessStatusCode(resp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSuccessStatusCode", reflect.TypeOf((*MockHTTPClient)(nil).IsSuccessStatusCode), resp)
}
