name: Deployment

on:
  push:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18
          cache: true
      - run: go get .

      - name: Test Integration
        run: make test-integration

      - name: Test Benchmark
        run: make test-benchmark

      - name: Test Unit
        run: make test-unit